packages/runtime/example/nested-components/index.html, packages/runtime/src/App.tsx, packages/runtime/src/components/_internal/Slot.tsx, packages/runtime/src/components/chakra-ui/Button.tsx, packages/runtime/src/components/chakra-ui/Tabs.tsx, packages/runtime/src/registry.tsx, packages/runtime/src/store.ts, packages/runtime/src/traits/core/slot.ts
impl #11 
To implement slot trait, we do the following changes
1. Nestable components should embed <Slot /> inside itself.
2. Attachable components should use the slot trait to indicate which container they will be attached to.
During app render, we will resolve the nested relation by traversing the components spec. This process will return top-level components and a resolved slots tree.
Top-level components will be rendered directly. The resolved slots tree will be passed into every <Slot />, so the embed <Slot /> can render which has been attached to itself.
=> impl slot trait

packages/core/__tests__/application.spec.ts, packages/core/src/application.ts, spec/zh_CN/SPEC.md
related to #54
If users naming component with id 'input-1', it may be hard to be
used in the expression, because 'input-1' is not a valid JS variable
name.
So we update the spec to make sure component ids are valid JS variable
names.
According to https://stackoverflow.com/a/1661249, a valid JS variable
name can be a big set. In this patch, we just force users to pass
a simple and limited RegExp, which keeps the application simple and readable.
TODO: validate component ids are not keywords.
=> update the spec of component ids in the spec

packages/editor/index.html, packages/editor/package.json, packages/editor/playground.html, packages/editor/src/components/ComponentForm/ComponentForm.tsx, packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx, packages/editor/src/components/ComponentForm/EventTraitForm/EventTraitForm.tsx, packages/editor/src/components/ComponentForm/GeneralTraitFormList/AddTraitButton.tsx, packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitForm.tsx, packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitFormList.tsx, packages/editor/src/components/ComponentsList/ComponentList.tsx, packages/editor/src/components/Editor.tsx, packages/editor/src/components/KeyboardEventWrapper.tsx, packages/editor/src/components/StructureTree/ComponentTree.tsx, packages/editor/src/components/StructureTree/StructureTree.tsx, packages/editor/src/main.tsx, packages/editor/src/metaUI.tsx, packages/editor/src/operations/AppModelManager.ts, packages/editor/src/operations/useAppModel.ts, packages/editor/src/playground.tsx, packages/editor/vite.config.ts, packages/runtime/package.json, packages/runtime/vite.config.ts, packages/vite-plugins/README.md, packages/vite-plugins/index.js, packages/vite-plugins/package.json
In this PR, we allowed the editor package to re-use the examples of the runtime package. The entry of the editor examples is `playground.html`.
During refactoring the editor components, I found rely on the global variables like `registry`, `appModelManager` makes it hard to manage the states of an editor instance, and impossible to create two editor instances at the same time.
So this commit(b7207db8b0f01472558a360b0ead482aa400f775) remove global variables, which introduce more props by-pass that can be optimized in the future.
=> add playground to editor

packages/core/src/component.ts, packages/editor/src/components/ComponentForm/ComponentForm.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/ArrayField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/BooleanField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/MultiSchemaField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/NullField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/NumberField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/ObjectField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/SchemaField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/StringField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/UnsupportedField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/fields.tsx, packages/editor/src/operations/AppModelManager.ts, packages/editor/src/operations/Operations.ts, packages/runtime/__tests__/parseTypeBox.spec.ts, packages/runtime/src/utils/parseTypeBox.ts
issue: https://github.com/webzard-io/meta-ui/issues/109
The design of our JSON schema form is largely inspired by [rjsf](https://github.com/rjsf-team/react-jsonschema-form). In the form, there are two main concepts: `schema`(the static JSON schema) and `formData`(the dynamic runtime form value).
The architecture:
The form will read from the schema and pass the schema to the `SchemaField`. `SchemaField` will iterate the passed-in schema and choose the right field to handle it. For example, if the `SchemaField` gets a schema with type `object`, it will render an `ObjectField`.
We will have the following fields:
[x] `ObjectField`
[x] `StringField`
[x] `ArrayField`
[x] `BooleanField`
[x] `MultiSchemaField`, for `anyOf` and `oneOf` schemas.
[x] `NumberField`
[x] `NullField`
[x] …
=> Introduce JSON schema form as the default component properties form

examples/list/listModule.json, packages/runtime/__tests__/expression.spec.ts, packages/runtime/src/App.tsx, packages/runtime/src/services/stateStore.ts
This PR is about #113 , and helps module mechanism. 
English Version
`'{{ value }}'` '100'
`'{{ value.toUppercase() }}'`'ABC'
`'Hello, {{ value }}!'`'Hello, world'
`'{{ $listItem.name }} is {{ $listItem.age }} years old'`'Tom is 10 years old'
`'{{ $listItem.name }} is in {{ root.listTitle }} list'`'Tom is in UserList list'
Expressions support nesting, which is useful in the context of lists and modules. E.g:
`'{{ {{$listItem.value}}Input.value + {{$moduleId}}Fetch.value }}!'`
The parser will step by step `eval` and concatenate strings from the inside to the outside.
Note that in most cases, it is best to always add a space inside `{{` and `}}`, otherwise the parser will not be able to parse it normally. The following is the wrong way of writing:
`{{{}}}`
`{{{id: 1}}}` (change it to `{{ …
=> refactor parseExpression function

packages/runtime/src/services/ImplWrapper.tsx, packages/runtime/src/traits/core/hidden.tsx, packages/runtime/src/types/RuntimeSchema.ts
Currently, we only support hidden a component visually, which is not good for performance and miss the control of the component life cycle.
In this PR, I've added a new prop to the hidden trait, which controls the hidden is visually or logically.
The short of this implementation is it could not re-use the `props` field in `TraitResult`, so I added a new field `unmount` to let the `ImplWrapper` know what to do. This makes the `TraitResult` type looks casual, any suggestion on the type will be appreciated.
=> support unmount component when hidden

packages/editor/src/main.tsx, packages/runtime/src/index.ts, packages/runtime/src/services/util-methods.ts
1. Export Slot and ModuleRenderer which is useful for components developers.
2. Add a temporary way to call global methods.
3. Allow customize editor container.
The second part is a workaround. Currently, we allow inject dependencies to eval scope, but when users are using events trait, there is no way to these dependencies.
=> export internal components and allow call global method

packages/editor/src/components/ComponentForm/ComponentForm.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/ArrayField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/MultiSchemaField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/ObjectField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/SchemaField.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/fields.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/ModuleWidget.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/widgets.tsx
With this PR, component developers can define the editor widget of certain fields like this:
```js
module: Type.Object(RuntimeModuleSchema.properties, {
widget: 'module',
})
```
In the future, we can support registering custom widgets to an editor, then developers can define an editor widget along with the component implementation.
=> introduce widgets and impl module widget

packages/editor/package.json, packages/editor/postcss.config.js, packages/editor/src/components/CodeEditor/CssEditor.tsx, packages/editor/src/components/CodeEditor/SchemaEditor.tsx, packages/editor/src/components/CodeEditor/StateEditor.tsx, packages/editor/src/main.tsx, packages/editor/src/playground.tsx, packages/editor/src/styles.css, packages/runtime/package.json, packages/runtime/postcss.config.js, packages/runtime/src/components/_internal/GridLayout.tsx, packages/runtime/src/index.ts, packages/runtime/src/style.css, yarn.lock
Some frameworks like Next.js does not like global CSS from node
modules, so we are going to bundle CSS into a single file with
postcss.
ref: https://github.com/vercel/next.js/discussions/27953
=> manage editor styles in a single CSS

packages/core/package.json, packages/editor/package.json, packages/runtime/package.json
Building to es5 causes sourcemap broke and currently no solution. It may be a bug of tsup.
=> revert build to es5

packages/chakra-ui-lib/src/components/Tabs.tsx, packages/runtime/src/components/_internal/ImplWrapper.tsx, packages/runtime/src/types/Component.ts
when only one child in slot, set slot to ReactElement instead of array
=> fix: set slot to different types depend on slot children's num

packages/editor/src/services/AppStorage.ts, packages/editor/src/utils/addModuleId.ts
By making `addModuleId` and `removeModuleId` immutable to avoid directly modifing object values in mobx.
=> fix bug that the editor will crash after switching module

.eslintrc.json
Fix #253 
The only thing we need to do is to put the prettier eslint config to the last of the extensions, then it will override other rules to avoid conflict.
Quote from its documentation
> Make sure to put it last, so it gets the chance to override other configs.
=> put prettier eslint config to the last

packages/editor/src/components/Editor.tsx, packages/editor/src/components/EditorMaskWrapper/EditorMask.tsx, packages/editor/src/components/EditorMaskWrapper/EditorMaskWrapper.tsx, packages/editor/src/components/WarningArea.tsx, packages/runtime/src/App.tsx
The coordiantes system of mask looks like this. It is established by get all the rect of elements and **will not change** until any component updates or resizes.
There is one thing that have to be taken in to consider, which is the **scroll offset**. If the app has been scrolled when we get the rect of elements, the rects value will include scroll offset, therefore the whole coordinates system will have offset. So we must record this offset at the moment we establish the system, and correct the offset in the later calculation.
One more thing to mention, the app could be scrolled even after the system is established. So there are 2 kinds of scroll offset: the current offset and the offset snapshot when we establish the system. They are different.
=> fix: mask position calculation is wrong after scrolling

packages/runtime/__tests__/expression.spec.ts, packages/runtime/src/services/StateManager.ts
By introducing a looking ahead algorithm, now we can correctly parse expressions like `{{{a: 1}}}`.
=> improve the expression parser

packages/editor/src/components/StructureTree/ComponentItemView.tsx, packages/editor/src/components/StructureTree/ComponentTree.tsx, packages/editor/src/components/StructureTree/DropComponentWrapper.tsx, packages/editor/src/components/StructureTree/StructureTree.tsx, packages/editor/src/operations/branch/component/createComponentBranchOperation.ts, packages/editor/src/operations/branch/component/moveComponentBranchOperation.ts, packages/editor/src/operations/leaf/component/adjustComponentOrderLeafOperation.ts
#292 
1. Improve dragging interaction
2. Prevent component from being dragged to its self or children.
Now the component tree drag interaction is like notion.
https://user-images.githubusercontent.com/12260952/155073622-9613e6eb-28ce-44c2-b521-0e824716f3eb.mov
=> fix component tree bug and improve interaction

packages/editor/src/components/CodeEditor/ExpressionEditor.tsx, packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/ExpressionWidget.tsx
Ref: https://github.com/webzard-io/sunmao-ui/issues/252
=> feat: improve expression editor[fix #252]

examples/box/index.json, examples/conditional-render/hidden.json, examples/dialog/index.json, examples/fetch-list/lazy.json, examples/form/formInDialog.json, examples/input-components/inputValidation.json, examples/input-components/numberInput.json, examples/radio/index.json, examples/router/hash.json, examples/router/index.json, examples/router/params.json, examples/table/staticData.json, examples/table/tableWithForm.json, packages/chakra-ui-lib/src/components/Table/Table.tsx, packages/chakra-ui-lib/src/components/Table/TableTd.tsx, packages/editor/src/components/DataSource/ApiForm/ApiForm.tsx, packages/runtime/package.json, packages/runtime/src/components/_internal/ImplWrapper.tsx, packages/runtime/src/components/_internal/ModuleRenderer.tsx, packages/runtime/src/services/StateManager.ts, packages/runtime/src/services/apiService.ts, packages/runtime/src/traits/core/Event.tsx, packages/runtime/src/traits/core/Fetch.tsx, packages/runtime/src/types/trait.ts, yarn.lock
1. Fix: event handler is called async when `wait.time` is `0`.
2. Fix: `deepEvalAndWatch` method generates mutable object.
In order to get the latest state, every time before an event handler is going to be called, **the handler schema need to be evaled again**. Otherwise, the event handler will be called with state of last frame.
This logic needs to be added to component **manually**. But only few components need to add it because these components need to trigger events by itself, like button in `table` or `onComplete` in `fetch`. Most components' events are handled by event trait.
=> Make sure event handler is called in sync order and with the lateset state.

packages/chakra-ui-lib/src/components/Dialog.tsx, packages/editor/src/components/EditorMaskWrapper/EditorMask.tsx, packages/editor/src/components/EditorMaskWrapper/EditorMaskWrapper.tsx, packages/editor/src/components/StructureTree/ComponentTree.tsx, packages/editor/src/components/StructureTree/DropComponentWrapper.tsx, packages/editor/src/components/StructureTree/StructureTree.tsx, packages/editor/src/init.tsx, packages/runtime/src/App.tsx, packages/runtime/src/components/_internal/ImplWrapper.tsx, packages/runtime/src/types/application.ts
1. EditorMask support components in dialog #291 
2. fix: cannot drop component after components which have no slots
This implementation is kind of workaround for now. The key point is to filter the elements in dialog by detecting whether an element is child of `dialogContainerElement`.
The limitation of this way is that it cannot detect modals which append to body or multiple modals situation.
The ultimate solution maybe adding a z-axis in `rectMap`. But since we don't have multiple dialogs or popover for now, so we can implement it in the future.
=> EditorMask support components in dialog

packages/arco-lib/src/generated/types/Table.ts, packages/editor/src/components/Editor.tsx, packages/editor/src/components/EditorMaskWrapper/EditorMask.tsx, packages/editor/src/components/EditorMaskWrapper/EditorMaskWrapper.tsx
1. Increase to canvas padding to avoid the top component's label hiding.
2. Move label to the top of component to avoid label covering the component.
=> improve editor mask label

packages/runtime/src/services/Registry.tsx, packages/runtime/src/traits/core/ArrayState.tsx, packages/runtime/src/traits/core/Event.tsx, packages/runtime/src/traits/core/Fetch.tsx, packages/runtime/src/traits/core/Hidden.tsx, packages/runtime/src/traits/core/LocalStorage.tsx, packages/runtime/src/traits/core/Slot.tsx, packages/runtime/src/traits/core/State.tsx, packages/runtime/src/traits/core/Style.tsx, packages/runtime/src/traits/core/Validation.tsx, packages/runtime/src/types/trait.ts
Trait is pure function, so it can not have state. But in the development, we find many trait need state, like `fetch`, `state`...
The solution is to wrap trait function with another factory function. Trait can store state in the closure. 
The `registerTrait` method and `SunmaoLib` accept `TraitImplFactory` instead of `TraitImpl` now.
=> add TraitImplFactory

packages/editor/src/components/DataSource/ApiForm/ApiForm.tsx, packages/editor/src/components/DataSource/ApiForm/Body.tsx, packages/editor/src/components/DataSource/DataSource.tsx, packages/runtime/src/components/core/FileInput.tsx, packages/runtime/src/services/Registry.tsx, packages/runtime/src/traits/core/Fetch.tsx, packages/runtime/src/types/traitPropertiesSchema.ts
1. add a core component: FileInput. FileInput can select files and store files in `stateStore`.
2. add a `bodyType` property for fetch trait. Because upload file need body to be `FormData` instead of JSON. Now support `formData` and `json`.
The settings of uploading file.
=> Add FileInput Component

packages/runtime/src/services/StateManager.ts
To fix this bug. If there is an space at the end of expression accidentally, the expression will be evaled as string, instead of an object, which is not expected.
=> trim expression before eval

packages/arco-lib/src/components/Tabs.tsx, packages/arco-lib/src/generated/types/Tabs.ts, packages/editor/src/components/Editor.tsx, packages/editor/src/components/StructureTree/StructureTree.tsx, packages/editor/src/services/EditorStore.ts
1. Add `setActiveTab` methods to tabs component.
2. Keep the scroll bar of each panel of explore menu tabs independent,previously, each panel under a tabs component shared the scroll bar of the parent element, so it could not maintain its original position when switching between tabs.
3. Fixed a bug where repeatedly clicking on the currently edited application (repeatedly clicking on an app or module) would cause the `stateManager's` store to be cleared
=> fix some bugs

packages/editor-sdk/src/components/Form/ArrayTable.tsx, packages/editor-sdk/src/components/Widgets/EventWidget.tsx, packages/editor-sdk/src/components/Widgets/PopoverWidget.tsx, packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx, packages/editor/src/components/Editor.tsx, packages/editor/src/components/StructureTree/ComponentTree.tsx, packages/editor/src/components/StructureTree/DropComponentWrapper.tsx, packages/editor/src/components/StructureTree/StructureTree.tsx
The editor is slow rendering when selecting the component in the huge application, so I improve the performance in these ways:
- Lazy loading.
Render the `Popover`, `Accordion` and etc. components when they are opened instead of mounted.
- Extract the changeable props from the heavy component to the HOC.
The `selectedComponentId` prop of `ComponentTree` component would be changed which would make the whole tree update when selecting the component, but the `isSelected` may not change. Thus, I create a HOC to read the `selectedComponentId` in the store and calculate the `isSelected`.
The rendering's time before optimization takes 258.6ms.
The rendering's time after optimization takes 74.3ms.
=> feat: improve the editor performance

package.json, packages/core/src/module.ts, packages/editor-sdk/src/components/Form/RecordEditor.tsx, packages/editor/src/components/Explorer/ExplorerForm/ExplorerForm.tsx, packages/editor/src/components/Explorer/ExplorerForm/ModuleMetaDataForm.tsx, packages/editor/src/components/Explorer/ExplorerTree.tsx, packages/editor/src/constants/index.ts, packages/editor/src/services/AppStorage.ts, packages/editor/src/services/EditorStore.ts, packages/runtime/src/services/StateManager.ts, yarn.lock
Add `spec.exampleProperties` into the module schema, it is only used by the editor to mock the module properties.
When switching to editing the module components, the editor would set `spec.exampleProperties`'s values into `stateManager.dependencies` to inject the properties.
=> feat(editor): add module mock properties in the editor

package.json, packages/arco-lib/package.json, packages/editor-sdk/package.json, packages/editor/package.json, packages/shared/package.json
`git add` causes bug after we use commitlint, so I removed it.
Reason: https://github.com/okonet/lint-staged/issues/775
=> fix bug: fail to release pacakge because of commitlint

packages/editor/src/components/ComponentForm/GeneralTraitFormList/AddTraitButton.tsx
If I click the button 'Add Trait', the popup form will be covered by some section titles with higher z index values.
Change the z index value of that form to 100. '100' is equal to the z-index of section titles.
Effect applied this fix:
=> fix: trait form is covered by section titles

packages/arco-lib/src/components/Dropdown.tsx, packages/arco-lib/src/generated/types/Dropdown.ts
Currently, the text of the Dropdown component is fixed with the text 'Click'.
This component isn't helpful unless the content is customisable.
=> feat(arco): enable to customize button content of Dropdown component

packages/arco-lib/src/components/Input.tsx, packages/arco-lib/src/components/TextArea.tsx
The Input and Textarea components (arco design) don't have a setInputValue method as Chakra's input component does. But I think this method is very helpful for other components to control the value of the Input component.
=> feat(arco): expose 'setInputValue' method for Input and Textarea

packages/arco-lib/src/components/Table/Table.tsx, packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
bug reproduction:
1. add CSS style 'padding: none;' to a style trait.
2. change the width or height value to '100px'.
3. Then the schema's corresponding part changes to 
Currently, when a user clicks the table's radio or checkbox, the onRowClick method is also triggered.  In the general case, the row selection operation (clicking a checkbox) should be separated from clicking a row item. 
Thinking about a use case: a user clicks a row to open a model which shows detailed messages about it. The user doesn't want to open the dialogue when clicking the checkbox to select this row.
=> fix:  css style string is parsed to char array accidentally

packages/editor/src/components/EditorMaskWrapper/EditorMaskManager.ts
Fix it by adding scroll compensation to the mouse position.
https://user-images.githubusercontent.com/12260952/174958588-d3106f7e-4795-4e9e-9090-d55208552361.mov
=> fix(mask): fix the bug that mask location is wrong position when editor is scrolled

packages/runtime/src/traits/core/Hidden.tsx
The hidden trait's `display: none` would be overwritten by the component styles or the style trait.
I use the `&&&& { display: none }` to increase its priority which is greater than the style trait's `&&&`.
=> fix: increase the hidden trait style priority

packages/editor-sdk/src/components/Form/ExpressionEditor.tsx, packages/editor-sdk/src/components/Widgets/ExpressionWidget.tsx
When inputting the expression like `{{state.value.concat}}` would make the component form crash, because when passing a function as a value to React's `setState`, React would execute the function instead of setting it as a value.
=> fix(ExpressionEditor): fix the error happening when evaledValue is a function

packages/arco-lib/src/components/Slider.tsx
The tooltip can now be formatted with formatTooltip slot
=> feat(arco/Slider): add formatTooltip slot

packages/editor-sdk/package.json, packages/editor-sdk/src/components/Widgets/SpecWidget.tsx, packages/editor/__tests__/model/componentModel.spec.ts, packages/editor/__tests__/validator/mock.ts, packages/runtime/__tests__/_internal/Text.spec.tsx, packages/runtime/package.json, packages/runtime/src/components/_internal/Text.tsx, yarn.lock
Remove react-markdown because its 6.x version will cause vite build error and 7.x+ version only export esm package which blocks ssr.
=> fix(runtime): remove react-markdown

packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
Because <button> cannot be nested, so i render the inner button as div.
=> fix(styleTraitForm): fix nested button warning

examples/tabs/index.json, packages/chakra-ui-lib/src/components/Tabs.tsx, packages/runtime/src/components/_internal/ImplWrapper/ImplWrapper.tsx, packages/runtime/src/components/_internal/ImplWrapper/ImplWrapperMain.tsx, packages/runtime/src/components/_internal/ImplWrapper/UnmountImplWrapper.tsx, packages/runtime/src/components/_internal/ImplWrapper/hooks/useSlotChildren.tsx, packages/runtime/src/types/component.ts
Previously, we introduce if condition to the slot trait, which helps
render slot element conditionally. But it is not easy for a component
developer to implement fallback UI of a slot, because neither the
if condition is true or false, the slot elements function will return
the ImplWrapperMain component.
This patch brings a new way to implement fallback UI: pass the
fallback UI as the second parameter of the slot elements function.
So in the ImplWrapper, we can fall back to the passed in UI.
Before:
After:
=> feat(runtime): pass slot fallback into slot elements

packages/editor/src/components/KeyboardEventWrapper.tsx
Now we can paste component into the components that don't have `'content'` slot.
=> fix(paste): paste component into the first slot instead of 'content' slot

packages/shared/__tests__/spec.spec.ts, packages/shared/src/utils/spec.ts
The optional properties' field of newly created component/trait does not show in form. For example, the hidden trait has a `visually` property and it does not show.
This is because the form is rendered from the `defaultValue` generated from spec. And the `generateDefaultValueFromSpec` function will not generate value if a property is optional. 
So I changed the logic of `generateDefaultValueFromSpec`. It will generate default value for optional property now.
=> fix(shared): use default value instead of  undefined when generate default value from spec

packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitForm.tsx
The trait form fields are generated from trait's properties, so if there is a property which is not in its spec, this field spec will be `undefined`, and the form will crash.
reproduce schema
```
{
"version": "sunmao/v1",
"kind": "Application",
"metadata": {
"name": "some App"
},
"spec": {
"components": [
{
"id": "state0",
"type": "core/v1/dummy",
"properties": {},
"traits": [
{
"type": "core/v1/state",
"properties": {
"key": "value",
"initialValue": "hahaha",
"value": ""
}
}
]
}
]
}
}
```
=> fix(traitForm): trait form will crash if the trait has a property that is not in its spec

packages/editor/src/components/StructureTree/StructureTree.tsx
This pr can fix the problem that the component tree scrolls too frequently.
=> fix(structureTree): if a component item is already in viewport, then don't scroll it into view

packages/editor-sdk/src/components/Widgets/ArrayField.tsx, packages/editor-sdk/src/components/Widgets/BooleanField.tsx, packages/editor-sdk/src/components/Widgets/ExpressionWidget.tsx, packages/editor-sdk/src/components/Widgets/NumberField.tsx, packages/editor-sdk/src/types/editor.ts, packages/runtime/__tests__/ImplWrapper/ImplWrapper.spec.tsx, packages/runtime/__tests__/_internal/List.spec.tsx, packages/runtime/__tests__/_internal/ModuleRenderer.spec.tsx, packages/runtime/__tests__/expression.spec.ts, packages/runtime/src/services/StateManager.ts
1. When switching from expression mode, editor should immediately save once.
2. Converting data types should not be done by `stateManager`, but by the widget.
3. Each Widget should convert the incoming value , and if the widget can not render value, it should report an error, not modify the schema.
4. ExpressionWidget should not convert the user input string.
=> Refactor some expressions logics

packages/editor-sdk/src/components/Widgets/EventWidget.tsx, packages/editor-sdk/src/components/Widgets/PopoverWidget.tsx, packages/editor-sdk/src/constants/index.ts, packages/editor-sdk/src/constants/widget.ts
when clicking the outside node which would stop propagation, it can't close the popover widget
=> fix: fix clicking outside can't close the popover widget

packages/arco-lib/src/sunmao-helper.ts, packages/chakra-ui-lib/src/components/Table/spec.ts, packages/core/package.json, packages/core/src/component.ts, packages/core/src/metadata.ts, packages/editor/src/AppModel/ComponentModel.ts, packages/editor/src/components/ComponentsList/ComponentList.tsx, packages/editor/src/validator/SchemaValidator.ts, packages/editor/src/validator/interfaces.ts, packages/runtime/src/components/_internal/ImplWrapper/ImplWrapperMain.tsx, packages/runtime/src/components/_internal/ImplWrapper/UnmountImplWrapper.tsx, packages/runtime/src/services/Registry.tsx, packages/runtime/src/types/component.ts, packages/runtime/src/types/trait.ts, packages/runtime/src/utils/buildKit.ts, packages/shared/src/types/utils.ts
The previous approach causes the 'exampleProperties' error when the component property is Record type.
Because the type of `T & {
metadata: { exampleProperties: DeepPartial<Static<T['spec']['properties']>> };
}` is a hack way to validate the `exampleProperties`, it would cause errors in some situations. 
This PR uses the generics type as the `exampleProperties` type, then fixes the errors.
=> fix: fix the `exampleProperties` type errors

packages/editor/src/components/ComponentForm/ComponentForm.tsx
When selecting a component, it would change the properties' values.
1. Refresh
2. Select the component whose `ifCondition` doesn't use the expression
3. Select another component whose `ifCondition` uses the expression
4. You can see the expression would be a switch component, and the `ifCondition` value is `true`
https://user-images.githubusercontent.com/25414733/185020448-99f30db1-3e56-47b9-8739-283a5af2f5a5.mov
The different components would reuse the form, when selecting another component it would trigger the widget's `useEffect` and then would change the value.
Add the different keys for the different component forms.
=> fix: fix selecting component would change the properties' values issue

packages/arco-lib/src/components/Table/Table.tsx, packages/chakra-ui-lib/src/components/Table/Table.tsx, packages/chakra-ui-lib/src/components/Table/TableTd.tsx, packages/chakra-ui-lib/src/components/Table/TableTypes.ts, packages/chakra-ui-lib/src/components/Table/spec.ts, packages/chakra-ui-lib/src/components/Tabs.tsx, packages/runtime/__tests__/testLib/Tabs.tsx, packages/runtime/src/components/_internal/ImplWrapper/ImplWrapper.tsx, packages/runtime/src/components/_internal/ImplWrapper/ImplWrapperMain.tsx, packages/runtime/src/components/_internal/ImplWrapper/SlotReciver.tsx, packages/runtime/src/components/_internal/ImplWrapper/UnmountImplWrapper.tsx, packages/runtime/src/components/_internal/ImplWrapper/hooks/useRuntimeFunctions.ts, packages/runtime/src/components/_internal/ImplWrapper/hooks/useSlotChildren.tsx, packages/runtime/src/components/core/List.tsx, packages/runtime/src/index.ts, packages/runtime/src/services/SlotReciver.tsx, packages/runtime/src/services/StateManager.ts, packages/runtime/src/traits/core/Event.tsx, packages/runtime/src/traits/core/Fetch.tsx, packages/runtime/src/types/application.ts, packages/runtime/src/types/component.ts, packages/runtime/src/types/trait.ts
Overview:
The main idea of this patch is to set slot props to a reactive store instead of passing them as React props to the slot children elements. On the other hand, we put fallback elements into a Map either, to avoid of passing them as props.
Same as other state management in sunmao, the component will subscribe to the slot store to get the latest value of slot props.
Same as component id, we need a way to identify every slot prop in the store. So we add a new parameter key to the `getSlot` function, where [component id, slot name, key] will be a unique identifier.
> Currently, the PR you are reviewing only migrates several components with the new `key` parameter, but we will migrate all if the solution passes the review.
Another challenge is to subscribe to the slot store in an …
=> use the new data path to pass slot props and fallback elements

packages/arco-lib/src/methods/Message.ts, packages/chakra-ui-lib/src/components/Types/Toast.ts, packages/chakra-ui-lib/src/index.ts, packages/runtime/src/services/Registry.tsx, packages/runtime/src/types/utilMethod.ts
Refactor `UtilMethodFactory` type to keep the same style with `TraitFactory`.
before:
`export type UtilMethodFactory = () => ImplementedUtilMethod<any>[]`
after:
`export type UtilMethodFactory = (sunmaoInstanceKey: string) => ImplementedUtilMethod<any>`
`sunmaoInstanceKey` is a new parameter. It is optional. Its purpose is to let the utilMethod know which Sunmao Instance is calling it.
=> refactor(runtime): refactor utilMethodFactory type

packages/runtime/src/services/SlotReciver.tsx
When the fallback is unmounted and called the `slotElements.xxx` again, the `SlotReceiver`'s `fallbacks[slotKey]` is `null`, thus it can't display the fallback correctly.
=> fix(slot): fix fallback disappearing when remounted

packages/editor-sdk/src/components/Widgets/BooleanField.tsx
Previously, booleanfield would accidentally convert undefined to true, now it only converts non-empty values
=> fix(BooleanField): convert only the values that exist

packages/runtime/__tests__/ImplWrapper/ImplWrapper.spec.tsx, packages/runtime/__tests__/ImplWrapper/mockSchema.ts, packages/runtime/__tests__/testLib/TestList.tsx, packages/runtime/__tests__/testLib/index.ts, packages/runtime/src/components/_internal/ImplWrapper/ImplWrapperMain.tsx, packages/runtime/src/components/_internal/ImplWrapper/UnmountImplWrapper.tsx, packages/runtime/src/services/StateManager.ts, packages/runtime/src/utils/initStateAndMethod.ts
This patch use a more solid way to check init state setup, instead of render count.
=> fix(runtime): fix #590, use an init set to check first time render

packages/editor/src/components/KeyboardEventWrapper.tsx, packages/editor/src/components/StructureTree/DropComponentWrapper.tsx
Component will disappear when dragged to a component that does not have `content` slot.
Now the component will be add to the first slot of parent.
=> fix(editor): component will disappear after being dragged

packages/editor-sdk/src/components/Widgets/ObjectField.tsx, packages/editor/src/components/Editor.tsx
1. Create a api DataSource
2. Click the expression button to change the `disabled` property to an expression and enter something
3. onblur, `disabled` content will automatically change to `{{true}}` ,And an additional `"key": "value"` field is added to the json
The reason for this bug is that api as a special DataSource will use `ApiForm` alone for rendering, but will also use `DataForm` for rendering as a common DataSource   
So when the disabled of the spec is modified to an `expression (e.g. {{xxx}})`, this spec is also passed to the `DataForm`.
But at this time the disabled in DataForm is not manually set to expression, so it will be rendered as `BooleanField` instead of `ExpressionWidget`   
And in BooleanFiled, it will turn the non-Boolean content to `true`, which will trigger the …
=> Fix the bug that api expression automatically changes to true

docs/en/install.md
Markdown tables were not rendered correctly due to spaces in header separators, removed spaces and formatted them.
=> fix(docs/en): fix and format markdown tables

packages/runtime/src/index.ts, packages/runtime/src/traits/core/Event.tsx, packages/runtime/src/traits/core/Fetch.tsx, packages/runtime/src/utils/runEventHandler.ts
Some 3rd-party custom trait will need to call `generateCallback`, so I export it and rename it to a more proper name.
=> refactor(runtime): export generateCallback and rename to runEventHandler

packages/editor/src/components/ComponentsList/ComponentFilter.tsx, packages/editor/src/components/Editor.tsx
Before fix:
* The filter component information entered by the user is reset after leaving the tab, and the  experience is poor
=> fix(editor): loss of state in ComponentList caused by tab switching

packages/arco-lib/src/components/Table/Table.tsx, packages/chakra-ui-lib/src/components/Table/TableTd.tsx, packages/editor-sdk/src/types/editor.ts, packages/runtime/__tests__/expression.spec.ts, packages/runtime/src/components/_internal/ImplWrapper/ImplWrapperMain.tsx, packages/runtime/src/components/_internal/ImplWrapper/hooks/useRuntimeFunctions.ts, packages/runtime/src/components/_internal/ModuleRenderer.tsx, packages/runtime/src/components/core/List.tsx, packages/runtime/src/services/StateManager.ts, packages/runtime/src/traits/core/Event.tsx, packages/runtime/src/types/component.ts, packages/runtime/src/types/trait.ts, packages/runtime/src/utils/runEventHandler.ts, packages/shared/__tests__/expression.spec.ts, packages/shared/src/utils/expression.ts
Remove the special handling of `$listItem` and `$i` in `parseExpression` to listen for changes in the properties content with these two attributes (currently most scenarios where these two are used are as property of `$slot`, no longer requires special treatment)      
For scenarios where $listItem and $i are used directly, the original spec should be evaled  
Resolves #622
=> remove evalListItem of parseExpression

packages/editor/src/components/CodeEditor/CodeEditor.tsx, packages/editor/src/services/EditorStore.ts
The reason for this bug is that the `UnControlled` component of `react-codemirror2` only updates [onBlur](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L204) in [componentDidMount](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L756), so subsequent calls to onBlur always get the cssProperties from the component mount in the closure context, thus overriding subsequent changes to the cssProperties
=> fix(CodeEditor): editing styles will override cssProperties
