smartxworks/sunmao-ui

packages/runtime/example/fetch-list/lazy.html
packages/runtime/example/fetch-list/nonLazy.html
packages/runtime/src/registry.tsx
packages/runtime/src/traits/core/fetch.tsx

1. first version of fetch trait.
2. example of lazy and non-lazy.
known-issue:
cannot detect internal change of headers with expression

initialize fetch trait

---

packages/runtime/example/input-components/index.html
packages/runtime/src/components/chakra-ui/Input.tsx
packages/runtime/src/registry.tsx

添加初步的 chakra input 组件，待补充 number 类型和 pin 类型

add initial chakra input component

---

packages/runtime/example/box/index.html
packages/runtime/src/components/chakra-ui/Box.tsx
packages/runtime/src/registry.tsx

add chakra box to runtime components

add chakra box component

---

packages/runtime/example/input-components/numberInput.html
packages/runtime/src/components/chakra-ui/Input.tsx
packages/runtime/src/components/chakra-ui/NumberInput.tsx
packages/runtime/src/registry.tsx

impl number input component

---

packages/runtime/example/checkbox/index.html
packages/runtime/src/components/chakra-ui/Checkbox.tsx
packages/runtime/src/registry.tsx

Implement the Chakra UI checkbox in the runtime package.

implement chakra checkbox #5

---

packages/runtime/example/stack/hstack.html
packages/runtime/example/stack/index.html
packages/runtime/example/stack/vstack.html
packages/runtime/src/components/chakra-ui/HStack.tsx
packages/runtime/src/components/chakra-ui/Stack.tsx
packages/runtime/src/components/chakra-ui/VStack.tsx
packages/runtime/src/registry.tsx

Implement Chakra UI stack components.

implement chakra ui stack #5

---

packages/runtime/package.json
packages/runtime/src/App.tsx
packages/runtime/src/components/chakra-ui/Box.tsx
packages/runtime/src/components/chakra-ui/Button.tsx
packages/runtime/src/components/chakra-ui/Input.tsx
packages/runtime/src/components/chakra-ui/Kbd.tsx
packages/runtime/src/components/chakra-ui/NumberInput.tsx
packages/runtime/src/components/chakra-ui/Table.tsx
packages/runtime/src/components/core/Text.tsx
packages/runtime/src/components/plain/Button.tsx
packages/runtime/src/store.ts
packages/runtime/src/traits/core/event.tsx
packages/runtime/src/traits/core/fetch.tsx
packages/runtime/src/traits/core/hidden.tsx
yarn.lock

Also, migrate components and traits.

impl expression evalutaion v2

---

packages/runtime/example/delete-button/index.html
packages/runtime/example/editor/index.html
packages/runtime/package.json
packages/runtime/src/App.tsx
packages/runtime/src/api-service.ts
packages/runtime/src/main.tsx
packages/runtime/src/store.ts
packages/runtime/src/traits/core/event.tsx
packages/runtime/src/util-methods.ts
yarn.lock

Implemented the API service feature on top of event emitter with
a concise protocol.
The protocol will use JSON as message format and only have one
type 'uiMethod' at this moment.

define UI API service, related to #9

---

.husky/_/husky.sh
.husky/pre-commit
.prettierrc
package.json

auto prettier staged file when commit

---

packages/runtime/example/box/index.html
packages/runtime/example/conditional-render/hidden.html
packages/runtime/example/delete-button/index.html
packages/runtime/example/fetch-list/nonLazy.html
packages/runtime/example/input-components/inputValidation.html
packages/runtime/example/router/hash.html
packages/runtime/example/router/index.html
packages/runtime/src/App.tsx
packages/runtime/src/components/_internal/Text.tsx
packages/runtime/src/components/chakra-ui/Input.tsx
packages/runtime/src/components/core/Text.tsx
packages/runtime/src/handler.ts
packages/runtime/src/registry.tsx
packages/runtime/src/store.ts
packages/runtime/src/traits/core/event.tsx
packages/runtime/src/traits/core/fetch.tsx
packages/runtime/src/traits/core/hidden.tsx
packages/runtime/src/traits/core/state.tsx
packages/runtime/src/traits/core/validation.tsx
packages/runtime/tsconfig.json

Refactor trait new implementation

---

packages/runtime/src/components/chakra-ui/Button.tsx
packages/runtime/src/components/plain/Button.tsx
packages/runtime/src/registry.tsx
packages/runtime/src/traits/core/event.tsx

event trait support any event name, not only click

event trait support any event name

---

packages/runtime/example/image-component/index.html
packages/runtime/src/components/chakra-ui/Image.tsx
packages/runtime/src/registry.tsx

Implement the Chakra UI Image in the runtime package.

Implement the Chakra UI Image in the runtime package.

---

packages/runtime/example/dialog/index.html
packages/runtime/example/dialog/list.html
packages/runtime/src/components/chakra-ui/Button.tsx
packages/runtime/src/components/chakra-ui/Dialog.tsx
packages/runtime/src/components/chakra-ui/Input.tsx
packages/runtime/src/registry.tsx

impl dialog component & add a list example with dialog component

feat: impl dialog component

---

packages/runtime/example/style/index.html
packages/runtime/src/components/chakra-ui/Tabs.tsx
packages/runtime/src/registry.tsx
packages/runtime/src/traits/core/style.tsx
packages/runtime/vite.config.ts

Add Style Trait.
Style Trait is based on emotion. Style Trait recieve property like:
```
{
'slotA': {
color: 'red'
},
'slotB': {
color: 'blue'
}
}
```
Components will use emotion to analyse css style, and apply it to its slot.

add style trait

---

packages/runtime/example/dialog/index.html
packages/runtime/example/dialog/list.html
packages/runtime/src/components/chakra-ui/Dialog.tsx
packages/runtime/src/components/chakra-ui/Input.tsx
packages/runtime/src/registry.tsx

It has been reviewd. https://github.com/webzard-io/meta-ui/pull/57

implement Dialog

---

packages/runtime/example/radio/index.html
packages/runtime/src/components/chakra-ui/Checkbox.tsx
packages/runtime/src/components/chakra-ui/CheckboxGroup.tsx
packages/runtime/src/components/chakra-ui/Radio.tsx
packages/runtime/src/components/chakra-ui/RadioGroup.tsx
packages/runtime/src/components/chakra-ui/Select.tsx
packages/runtime/src/registry.tsx

implement chakra ui radio component

feat: impl radio and radioGroup

---

packages/runtime/example/toast/index.html
packages/runtime/src/components/chakra-ui/Types/Toast.ts
packages/runtime/src/util-methods.ts
packages/runtime/src/utils/pickProperty.ts

- use chakra-ui toast createStandaloneToast as utils function to create a chakra-ui toast.
- implement a `pickProperty` function to ensure the type of parameter from mitt.

add chakra-ui toast.

---

packages/core/src/application.ts
packages/editor/src/components/Editor.tsx
packages/editor/src/components/StructureTree/StructureTree.tsx
packages/editor/src/operations/AppModelManager.ts
packages/editor/src/operations/useAppModel.ts
packages/runtime/src/components/chakra-ui/List.tsx
packages/runtime/src/services/ImplWrapper.tsx
packages/runtime/src/types/RuntimeSchema.ts

support drag component to tree to create

support drag component to tree to create

---

packages/editor/src/components/Editor.tsx
packages/editor/src/components/KeyboardEventWrapper.tsx

add keyboard event to undo and remove component

add keyboard event to undo and remove component

---

.prettierrc
packages/editor/package.json
packages/editor/src/components/CodeEditor/StateEditor.tsx
packages/editor/src/components/CodeEditor/index.ts
packages/editor/src/components/Editor.tsx
yarn.lock

According to other open-source projects' implementation, it looks like CodeMirror has the best choice to customize a low-code editor.
In this PR, we introduce CodeMirror and set up a basic JSON viewer for our store state.

introduce CodeMirror to implement code editors

---

packages/editor/package.json
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/FetchTraitForm/FetchTraitForm.tsx
packages/editor/src/main.tsx
packages/editor/tsconfig.json
yarn.lock

Also allow users to pass custom components, traits, and modules to the editor.

Bundle and publish editor package

---

packages/editor/package.json
packages/editor/src/components/ComponentWrapper.tsx
packages/runtime/package.json
packages/runtime/src/components/_internal/Text.tsx
packages/runtime/src/components/antd/TreeSelect.tsx
packages/runtime/src/components/chakra-ui/Button.tsx
packages/runtime/src/components/chakra-ui/Root.tsx
packages/runtime/src/components/core/GridLayout.tsx
packages/runtime/src/services/stateStore.ts
yarn.lock

* upgrade chakra to 1.7.1 to fix dark mode bug
* fix some style bug

fix some style bugs

---

packages/editor/src/components/CodeEditor/SchemaEditor.tsx
packages/editor/src/components/CodeEditor/index.ts
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/Editor.tsx
packages/editor/src/components/EditorHeader/EditorHeader.tsx
packages/editor/src/operations/AppModelManager.ts
packages/editor/src/operations/Operations.ts

embed schema editor

---

packages/editor/package.json
packages/runtime/package.json
packages/runtime/src/index.ts
packages/runtime/src/services/stateStore.ts
packages/runtime/src/utils/isNumeric.ts

Allow add custom dependencies for eval

---

packages/editor/src/operations/leaf/component/adjustComponentOrderLeafOperation.ts

move element for same level element.

fix adjust order operation

---

examples/dialog/dialogInList.json
examples/list/listModule.json
examples/module/index.json
packages/editor/src/AppStorage.ts
packages/editor/src/EditorStore.ts
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx
packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitForm.tsx
packages/editor/src/components/Editor.tsx
packages/editor/src/components/Explorer/Explorer.tsx
packages/editor/src/components/Explorer/ExplorerForm/AppMetaDataForm.tsx
packages/editor/src/components/Explorer/ExplorerForm/ExplorerForm.tsx
packages/editor/src/components/Explorer/ExplorerForm/ModuleMetaDataForm.tsx
packages/editor/src/components/Explorer/ExplorerForm/index.ts
packages/editor/src/components/Explorer/ExplorerTree.tsx
packages/runtime/src/components/_internal/Text.tsx
packages/runtime/src/utils/parseModuleSchema.ts

1. Can edit app's and module's metadata
2. fix module examples

Support edit app's and module's metadata in editor

---

packages/editor/src/EditorStore.ts
packages/editor/src/components/Explorer/ExplorerForm/ExplorerForm.tsx
packages/editor/src/components/Explorer/ExplorerTree.tsx
packages/editor/src/main.tsx
packages/editor/src/setup.ts
packages/runtime/src/components/_internal/ModuleRenderer.tsx
packages/runtime/src/services/stateStore.ts

1. clear stateStore after change app or module
2. fix cannot redo bug

fix module bugs

---

packages/editor/src/components/CodeEditor/CssEditor.tsx
packages/editor/src/components/CodeEditor/index.ts
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/GeneralTraitFormList/AddTraitButton.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/MultiSchemaField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/StringField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/fields.tsx
packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
packages/editor/src/components/ComponentForm/StyleTraitForm/index.ts
packages/editor/src/constants.ts

1. add style trait form
2. improve basic JSON schema fields UX

improve component form

---

packages/runtime/src/components/_internal/Slot.tsx
packages/runtime/src/components/chakra-ui/Tabs.tsx
packages/runtime/src/components/core/GridLayout.tsx

1. bypass props to children
2. render null when slot not set

improve the Slot component

---

examples/dialog/dialogInList.json
examples/list/listModule.json
examples/module/index.json
packages/editor/src/AppStorage.ts
packages/editor/src/EditorStore.ts
packages/editor/src/constants.ts
packages/runtime/src/components/_internal/ModuleRenderer.tsx
packages/runtime/src/services/registry.tsx
packages/runtime/src/utils/parseModuleSchema.ts

rename module components -> impl

---

packages/editor/src/components/Editor.tsx
packages/editor/src/components/GeneralModal.tsx
packages/editor/src/components/PreviewModal/PreviewModal.tsx

decouple the sunmao runtime instance in preview modal and editor view

---

packages/editor/__fixture__/application.ts
packages/editor/src/components/CodeEditor/CssEditor.tsx
packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
packages/runtime/src/traits/core/style.tsx

1. style trait accept array
2. refactor style trait form

refactor style trait

---

examples/dialog/dialogInList.json
packages/runtime/src/components/_internal/ImplWrapper.tsx
packages/runtime/src/traits/core/arrayState.tsx

fix dialogInList example

---

packages/editor/index.html
packages/editor/src/EditorStore.ts
packages/editor/src/components/ComponentWrapper.tsx

1. add support for multiple slot dragging by divide component by its slot.
- single slot nested drop handling
https://user-images.githubusercontent.com/29588646/148869916-93f7e02a-3877-492e-b2db-a5466de46cb2.mp4
- multiple slot drop handling
https://user-images.githubusercontent.com/29588646/148869940-6d57ce41-16fd-4b7a-8292-2e37fc42ab87.mp4

multiple slot drag handling

---

packages/editor/src/components/ComponentForm/EventTraitForm/EventTraitForm.tsx

fix(editor): fix can't create multiple events[fix #218]

---

packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/FetchTraitForm/FetchTraitForm.tsx
packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitFormList.tsx
packages/editor/src/components/ComponentWrapper.tsx
packages/editor/src/constants.ts
packages/editor/src/main.tsx
packages/editor/src/services/AppStorage.ts
packages/editor/src/services/EditorStore.ts
packages/editor/src/validator/rules/ComponentRules.ts
packages/runtime/src/types/TraitPropertiesSchema.ts

1. fix addModuleId multiple times bug
2. fix cannot add fetch trait bug

fix some editor bugs

---

packages/editor/package.json
packages/editor/src/components/CodeEditor/ExpressionEditor.tsx
packages/editor/src/components/CodeEditor/index.ts
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/ArrayField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/MultiSchemaField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/ObjectField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/SchemaField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/fields.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/ExpressionWidget.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/ModuleWidget.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/widgets.tsx
packages/editor/src/styles.css
yarn.lock

#225 
demo:
https://user-images.githubusercontent.com/13651389/151004594-8562fa49-a4f8-411e-b79c-89bb5f717553.mp4

Auto complete, part 1

---

packages/editor/__tests__/validator/component.spec.ts
packages/editor/__tests__/validator/mock.ts
packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx
packages/editor/src/components/ComponentForm/GeneralTraitFormList/AddTraitButton.tsx
packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
packages/editor/src/validator/rules/PropertiesRules.ts
packages/runtime/src/types/TraitPropertiesSchema.ts

1. fix style trait width bug
2. properties validator can detect window variables
3. event trait form can choose methods from trait
4. fetch trait defualt method is now default get

small bugs and impovements

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

chore: add issue and PR templates

---

packages/editor/src/AppModel/FieldModel.ts
packages/editor/src/components/ComponentForm/JsonSchemaForm/SchemaField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/UnsupportedField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/fields.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/ExpressionWidget.tsx
packages/editor/src/validator/utils.ts
packages/runtime/__tests__/expression.spec.ts
packages/runtime/src/services/stateStore.ts

#225 
1. Improve value serialization. Now we can use the expression editor in object and array values.
2. Fix multiline expression evaluation.

Auto complete: part 2

---

packages/editor/src/components/ComponentWrapper.tsx
packages/editor/src/components/Explorer/Explorer.tsx
packages/editor/src/components/Explorer/ExplorerForm/AppMetaDataForm.tsx
packages/editor/src/components/Explorer/ExplorerForm/ExplorerForm.tsx
packages/editor/src/components/Explorer/ExplorerForm/ModuleMetaDataForm.tsx
packages/editor/src/constants/layout.ts
packages/editor/src/services/AppStorage.ts

- improve the display of component wrapper's label
- fix the module form errors

fix(editor): change some styles and fix the problems of editor

---

packages/chakra-ui-lib/src/components/Types/Toast.ts
packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx
packages/editor/src/components/KeyValueEditor.tsx
packages/runtime/src/services/Registry.tsx

feat(editor): auto-complete the parameters of the method

---

packages/editor/src/components/CodeEditor/ExpressionEditor.tsx

https://user-images.githubusercontent.com/13651389/152966438-bcc97bbf-2b81-48e0-9c6f-1e9cc91b0b30.mp4

impl #225 trigger auto-complete when typing

---

packages/editor/src/components/CodeEditor/ExpressionEditor.tsx
packages/editor/src/components/CodeEditor/SchemaEditor.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/StringField.tsx
packages/editor/src/components/GeneralModal.tsx
packages/editor/src/styles.css

1. Support edit expression in modal view.
2. Use expression editor as the string field's default widget.
3. Improve DX with CodeMirror's excellent multiplex and overlay addon.
https://user-images.githubusercontent.com/13651389/153705384-b6af8ea3-b60d-432c-861a-27540b8f7658.mp4

Auto complete: improve DX

---

packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/SchemaField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/TopLevelField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/fields.tsx
packages/editor/src/validator/SchemaValidator.ts

Reference Issue: https://github.com/webzard-io/sunmao-ui/issues/261 https://github.com/webzard-io/sunmao-ui/issues/211
https://user-images.githubusercontent.com/96771399/153699843-3943cad4-766e-4753-9237-5a4d99b6da06.mov

feat: classify the properties of the components

---

packages/editor/src/components/ComponentForm/JsonSchemaForm/TopLevelField.tsx

1. fix the bug that set the value incorrectly when the property name and title do not match
2. fix the bug with incorrect sorting based on weight

fix: fix bugs with incorrect setting values and incorrect sorting

---

packages/chakra-ui-lib/src/components/Dialog.tsx
packages/editor/__tests__/model/componentModel.spec.ts
packages/editor/__tests__/model/mock.ts
packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx
packages/editor/src/components/ComponentForm/EventTraitForm/EventTraitForm.tsx
packages/editor/src/components/Editor.tsx
packages/editor/src/components/EditorMaskWrapper/DropSlotMask.tsx
packages/editor/src/components/EditorMaskWrapper/EditorMask.tsx
packages/editor/src/init.tsx
packages/editor/src/main.tsx
packages/editor/src/services/AppStorage.ts
packages/editor/src/services/EditorStore.ts
packages/editor/src/services/enum.ts

1. Fix the bug that page cannot scroll when chakra dialog is openning.
2. fix the bug that cannot drag component to a selected component
3. hide explorer
4. fix typo

fix some small bugs

---

packages/runtime/src/components/_internal/ImplWrapper.tsx

fix(runtime): remove executing trait from `useState`

---

packages/chakra-ui-lib/src/components/Types/Toast.ts
packages/editor/src/components/CodeEditor/ExpressionEditor.tsx
packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx
packages/editor/src/components/ComponentForm/FetchTraitForm/FetchTraitForm.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/ArrayField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/MultiSchemaField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/ObjectField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/SchemaField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/StringField.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/fields.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/ExpressionWidget.tsx
packages/editor/src/components/ComponentForm/JsonSchemaForm/widgets/widgets.tsx
packages/editor/src/components/DataSource/Api.tsx
packages/editor/src/components/DataSource/ApiForm/ApiForm.tsx
packages/editor/src/components/DataSource/ApiForm/Body.tsx
packages/editor/src/components/DataSource/ApiForm/Headers.tsx
packages/editor/src/components/DataSource/ApiForm/Params.tsx
packages/editor/src/components/DataSource/DataSource.tsx
packages/editor/src/components/DataSource/DataSourceItem.tsx
packages/editor/src/components/DataSource/StateForm/StateForm.tsx
packages/editor/src/components/Editor.tsx
packages/editor/src/components/Explorer/ExplorerForm/ModuleMetaDataForm.tsx
packages/editor/src/components/KeyValueEditor.tsx
packages/editor/src/services/EditorStore.ts

This PR includes these changes:
- prevent API and state form keyboard events to accidentally trigger operation shortcut
- fix the duplicated datasource ids problem
- support expression input and schema filed for datasource and event form
- make the `ExpressionEditor` to be controllable
The changes for form look like this:
Ref: https://github.com/webzard-io/sunmao-ui/issues/289

feat: improve datasource[fix #289]

---

packages/editor/src/components/CodeEditor/StateViewer.tsx
packages/editor/src/components/Editor.tsx

fix the warning in console when create a new component

---

packages/arco-lib/src/components/Form/FormControl.tsx
packages/arco-lib/src/components/Layout.tsx
packages/arco-lib/src/components/Menu.tsx
packages/arco-lib/src/components/Table.tsx
packages/arco-lib/src/components/Tabs.tsx
packages/arco-lib/src/examples/ExampleIndexPage.tsx
packages/arco-lib/src/examples/pages/layout/index.tsx
packages/arco-lib/src/examples/pages/layout/layoutWithMenu.ts
packages/arco-lib/src/examples/pages/tab/basicUsage.ts
packages/arco-lib/src/examples/pages/tab/index.tsx
packages/arco-lib/src/examples/pages/table/attributes.ts
packages/arco-lib/src/examples/pages/table/basicUsage.ts
packages/arco-lib/src/examples/pages/table/selection.ts
packages/arco-lib/src/examples/pages/table/sortAndFilter.ts
packages/arco-lib/src/generated/types/Layout.ts
packages/arco-lib/src/generated/types/Menu.ts
packages/arco-lib/src/generated/types/Table.ts
packages/arco-lib/src/generated/types/Tabs.ts
packages/arco-lib/src/sunmao-helper.ts

Improved components:
1. Menu
2. Layout
3. Tab
4. Table

Improve arco components & add examples

---

packages/editor/src/components/CodeEditor/StateViewer.tsx
packages/runtime/src/services/Registry.tsx
packages/runtime/src/traits/core/LocalStorage.tsx

1. implement localstorage trait
2. fix a bug that two updates to the store do not trigger a view refresh

implement localstorage trait

---

packages/arco-lib/src/generated/types/Cascader.ts
packages/arco-lib/src/generated/types/Checkbox.ts
packages/arco-lib/src/generated/types/Mentions.ts
packages/arco-lib/src/generated/types/Table.ts
packages/arco-lib/src/generated/types/TreeSelect.ts
packages/editor-sdk/package.json
packages/editor-sdk/src/components/Widgets/CategoryWidget.tsx
packages/editor-sdk/src/components/Widgets/ExpressionWidget.tsx
packages/editor-sdk/src/components/Widgets/ObjectField.tsx
packages/editor-sdk/src/components/Widgets/SchemaField.tsx

Fix the problems of invisible labels and displaying wrong widgets.

fix: fix some widgets' problems

---

packages/editor-sdk/src/components/Widgets/ExpressionWidget.tsx

fix stringify undefined value

---

packages/arco-lib/src/components/Checkbox.tsx
packages/arco-lib/src/components/Form/FormControl.tsx
packages/arco-lib/src/components/Input.tsx
packages/arco-lib/src/components/Radio.tsx
packages/arco-lib/src/components/Select.tsx
packages/arco-lib/src/generated/types/Checkbox.ts
packages/arco-lib/src/generated/types/Radio.ts
packages/arco-lib/src/generated/types/Select.ts
packages/runtime/src/components/core/Stack.tsx

Select, Input, Checkbox, Radio

Improve arco components

---

packages/chakra-ui-lib/src/components/Table/TableTypes.ts
packages/chakra-ui-lib/src/components/Table/spec.ts
packages/editor-sdk/package.json
packages/editor-sdk/src/components/Form/ArrayButtonGroup.tsx
packages/editor-sdk/src/components/Form/ArrayItemBox.tsx
packages/editor-sdk/src/components/Form/ArrayTable.tsx
packages/editor-sdk/src/components/Form/KeyValueEditor.tsx
packages/editor-sdk/src/components/Widgets/ArrayField.tsx
packages/editor-sdk/src/components/Widgets/CategoryWidget.tsx
packages/editor-sdk/src/components/Widgets/EventWidget.tsx
packages/editor-sdk/src/components/Widgets/ModuleWidget.tsx
packages/editor-sdk/src/components/Widgets/MultiSchemaField.tsx
packages/editor-sdk/src/components/Widgets/ObjectField.tsx
packages/editor-sdk/src/components/Widgets/PopoverWidget.tsx
packages/editor-sdk/src/components/Widgets/SchemaField.tsx
packages/editor-sdk/src/components/Widgets/index.ts
packages/editor-sdk/src/types/widget.ts
packages/editor-sdk/src/utils/schema.ts
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx
packages/editor/src/components/DataSource/ApiForm/ApiForm.tsx
packages/editor/src/components/DataSource/ApiForm/Body.tsx
packages/editor/src/components/DataSource/ApiForm/Headers.tsx
packages/editor/src/components/DataSource/ApiForm/Params.tsx
packages/editor/src/validator/SchemaValidator.ts

Changes:
- Adding a new field `path` to widget
- Adding a new popover widget
- Changing array widget
Screenshot:

feat: add the popover widget

---

packages/arco-lib/src/components/Table.tsx
packages/arco-lib/src/generated/types/Table.ts
packages/editor/src/components/Editor.tsx

1. add row click to table
2. component is clipped if necessary to fit the editor area
https://user-images.githubusercontent.com/96771399/158524393-d4880daa-492e-4371-b5a0-bee57e7d6f9e.mov

improve table component and editor area

---

packages/editor/src/components/DataSource/ApiForm/Basic.tsx
packages/runtime/src/components/_internal/ImplWrapper.tsx
packages/runtime/src/traits/core/Fetch.tsx
packages/runtime/src/types/traitPropertiesSpec.ts
packages/runtime/src/utils/resolveChildrenMap.ts
packages/runtime/src/utils/trait.ts

1. Remove hasFetched 
2. add disabled property
related issues: #356 #373

Remove hasFetched in fetch trait and add disabled property

---

packages/editor/src/components/Editor.tsx
packages/editor/src/components/EditorHeader/EditorHeader.tsx
packages/editor/src/components/ErrorBoundary.tsx
packages/editor/src/constants/enum.ts
packages/editor/src/init.tsx
packages/runtime/src/components/_internal/ImplWrapper.tsx
packages/runtime/src/components/core/Dummy.tsx
packages/runtime/src/traits/core/State.tsx
packages/runtime/src/types/trait.ts

- Refresh the app
https://user-images.githubusercontent.com/25414733/163127119-0e54b27f-8e26-44cf-a69d-fe00f6d3a383.mov
- Recover the app after fixing the errors
https://user-images.githubusercontent.com/25414733/163127320-43536026-871e-415c-9690-28008d449c81.mov

feat: add refresh button

---

packages/editor/src/components/CodeModeModal.tsx
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/Editor.tsx
packages/editor/src/components/EditorHeader/EditorHeader.tsx
packages/editor/src/components/EditorMaskWrapper/EditorMask.tsx
packages/editor/src/components/EditorMaskWrapper/EditorMaskWrapper.tsx
packages/editor/src/components/StructureTree/ComponentItemView.tsx
packages/editor/src/components/StructureTree/ComponentTree.tsx
packages/editor/src/components/StructureTree/StructureTree.tsx
packages/editor/src/services/EditorStore.ts

Improve UI Style

---

packages/editor/src/components/ComponentsList/ComponentFilter.tsx
packages/editor/src/components/ComponentsList/ComponentList.tsx

https://user-images.githubusercontent.com/96771399/170400740-bb559d28-b7d0-47c7-a908-f997fbc9ce41.mov

feat: components add filter by version

---

packages/chakra-ui-lib/src/components/Types/Toast.ts
packages/core/src/index.ts
packages/core/src/utilMethod.ts
packages/editor-sdk/src/components/Widgets/EventWidget.tsx
packages/runtime/src/services/Registry.tsx
packages/runtime/src/services/UtilMethodManager.ts
packages/runtime/src/types/utilMethod.ts
packages/runtime/src/utilMethods/ScrollIntoComponent.ts
packages/runtime/src/utils/buildKit.ts

BREAKING CHANGE:
use `type` to replace `name` when calling the method
ISSUES CLOSED: #248

feat(utilMethod): add spec to utilMethod

---

packages/arco-lib/src/components/Select.tsx
packages/editor-sdk/src/components/Form/ArrayTable.tsx
packages/editor/src/components/GeneralModal.tsx

1. feat(Select): add filter by text
2. fix(ArrayTable): fix the problem of length exceeding the table
previously:
now:
@MrWindlike PTAL         
3. feat(PreviewModal): fix the length of the component in the PreviewModal exceeds the modal
previously:
now:

Fix some style problems

---

packages/editor/src/components/EditorMaskWrapper/EditorMaskManager.ts

`EditorMask`  does not show because `onHTMLElementsUpdated` does not run in init.

fix an editor mask bug

---

packages/editor-sdk/src/components/Widgets/CategoryWidget.tsx
packages/editor-sdk/src/components/Widgets/EventWidget.tsx
packages/editor-sdk/src/components/Widgets/ObjectField.tsx
packages/editor-sdk/src/components/Widgets/SpecWidget.tsx
packages/editor-sdk/src/components/Widgets/StyleWidgets/SizeWidget.tsx
packages/editor-sdk/src/components/Widgets/index.ts
packages/editor-sdk/src/types/widget.ts
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/EventTraitForm/EventHandlerForm.tsx
packages/editor/src/components/ComponentForm/EventTraitForm/EventTraitForm.tsx
packages/editor/src/components/ComponentForm/FormSection.tsx
packages/editor/src/components/ComponentForm/GeneralTraitFormList/AddTraitButton.tsx
packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitFormList.tsx
packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
packages/editor/src/components/ComponentForm/style.ts
packages/editor/src/components/Editor.tsx
packages/editor/src/styles.css
packages/runtime/src/traits/core/Style.tsx
packages/shared/src/constants/core.ts

1. Add `SizeWidget` as example of style widgets.
2. Add `cssProperties` filed in style trait.
3. Refactor Component Form
Base on this branch, we can continue to implement more style widgets.
https://user-images.githubusercontent.com/12260952/170621826-cd605158-1c97-4a00-b60c-1bf6d6c4b453.mov

Refactor Component Form

---

packages/editor/src/components/EditorMaskWrapper/EditorMaskWrapper.tsx
packages/runtime/src/components/core/Iframe.tsx
packages/runtime/src/services/Registry.tsx
packages/runtime/src/types/component.ts
packages/shared/src/constants/core.ts

feat: add the iframe component

---

packages/editor-sdk/src/components/Widgets/SpecWidget.tsx
packages/editor/__tests__/model/componentModel.spec.ts
packages/editor/src/AppModel/ComponentModel.ts
packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitForm.tsx
packages/editor/src/components/ComponentForm/GeneralTraitFormList/GeneralTraitFormList.tsx
packages/editor/src/constants/index.ts
packages/runtime/src/traits/core/Slot.tsx

feat(editor): add the slot trait form

---

packages/editor-sdk/src/components/Widgets/StyleWidgets/FontWidget.tsx
packages/editor-sdk/src/components/Widgets/StyleWidgets/SizeWidget.tsx
packages/editor-sdk/src/components/Widgets/index.ts
packages/editor/src/components/ComponentForm/ComponentForm.tsx
packages/editor/src/components/ComponentForm/FormSection.tsx
packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
packages/editor/src/components/Editor.tsx
packages/editor/src/components/StructureTree/StructureTree.tsx
packages/shared/src/constants/core.ts

add font style widget

---

packages/editor-sdk/src/components/Widgets/StyleWidgets/SpaceWidget.tsx
packages/editor-sdk/src/components/Widgets/index.ts
packages/editor-sdk/src/types/widget.ts
packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx
packages/shared/src/constants/core.ts

Implementation of SpaceWidget:
https://user-images.githubusercontent.com/96771399/172525190-518753ee-31a8-42e3-9f01-7a94718aa1c2.mov
There are still some things that need to be done:
- **IMPORTANT**: Optimize the performance when mousemove, currently there are some serious frame drops, I feel that it is caused by too many re-rendering of react components, and need to find ways to optimize it in the future
- The SpaceWidget panel needs to be responsive

feat(StyleTraitForm): add SpaceWidget

---

packages/editor/src/components/ComponentForm/FormSection.tsx

fix(FormSection): fix  the property section not covering the code mirror window

---

packages/editor-sdk/package.json
packages/editor-sdk/src/components/Select/index.ts
packages/editor-sdk/src/components/Select/select.tsx
packages/editor-sdk/src/components/Select/style.ts
packages/editor-sdk/src/components/Select/utils.tsx
packages/editor-sdk/src/components/Widgets/EventWidget.tsx
yarn.lock

A more comprehensive select component based on [rc-select ](https://github.com/react-component/select)         
The implementation references ant-design
https://user-images.githubusercontent.com/96771399/173327888-1a8a6796-8a73-4309-be51-fbc45160a264.mov

feat: a more comprehensive select component based on rc-select

---

packages/editor-sdk/src/components/Widgets/ObjectField.tsx
packages/editor/src/components/DataSource/DataForm/DataForm.tsx

style(editor): fix the DataForm styles

---

packages/editor-sdk/package.json
packages/editor-sdk/src/components/Select/index.ts
packages/editor-sdk/src/components/Select/select.tsx
packages/editor-sdk/src/components/Select/style.ts
packages/editor-sdk/src/components/Select/utils.tsx
packages/editor-sdk/src/components/Widgets/EventWidget.tsx
yarn.lock

Accidentally merged it into main...

Merge rc-select pr from main to develop

---

packages/editor/src/components/DataSource/ApiForm/Body.tsx
packages/runtime/src/traits/core/Fetch.tsx

feat(runtime, editor): support raw body in fetch trait

---

packages/arco-lib/src/sunmao-helper.ts
packages/editor/src/main.tsx
packages/runtime/src/App.tsx
packages/runtime/src/components/_internal/ImplWrapper/ImplWrapperMain.tsx
packages/runtime/src/index.ts
packages/runtime/src/types/application.ts

Add a `isInEditor` argument in ImplProps for component to detect where is itself.
#330

feat(runtime): add isInEditor property

---

packages/editor-sdk/src/components/Widgets/StyleWidgets/SpaceWidget.tsx
packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx

Refactoring the SpaceWidget to make the style widget structure appear more compact
https://user-images.githubusercontent.com/96771399/177074752-3767d4eb-afd3-4d9d-aec6-2cc1783339a8.mov

refactor(SpaceWidget): refactor SpaceWidget

---

packages/editor/src/components/ComponentForm/StyleTraitForm/StyleTraitForm.tsx

fix(styleTraitForm): move remove style button position

---

packages/arco-lib/src/components/Collapse.tsx
packages/arco-lib/src/components/Input.tsx
packages/arco-lib/src/components/Mentions.tsx
packages/arco-lib/src/components/Menu.tsx
packages/arco-lib/src/components/Modal.tsx
packages/arco-lib/src/components/Popover.tsx
packages/arco-lib/src/components/Radio.tsx
packages/arco-lib/src/components/Tooltip.tsx

1. fix incorrect methods spec
2. fix a missing hooks dependency

fix: fix incorrect methods spec

---

packages/editor-sdk/src/components/Widgets/ExpressionWidget.tsx

When the value passing to the expression widget isn't the string type, it would be transformed by wrapping `{{}}` to it.
Submitting the expression code would parse the expression code by the spec type instead of the original value type.
The current implementation would use the original value type to parse the expression code which couldn't change the value type. For example, if I have a property with the `Type.Any()` type and its value is an object, I want to change it to the string type, but I can't do it.

fix: change the logic of the expression transform

---

packages/editor/src/components/Editor.tsx
packages/editor/src/components/PreviewModal/PreviewModal.tsx
packages/editor/src/init.tsx

fix the bug that preview modal will crash when there are dependencies in application.

fix(previewModal): pass dependencies to preview modal

---

packages/editor-sdk/src/components/Select/select.tsx
packages/editor-sdk/src/components/Select/style.ts

Mount popup to `document.body` to solve some positioning problems

feat(select): put popup to body

---

packages/runtime/__tests__/ImplWrapper/ImplWrapper.spec.tsx
packages/runtime/__tests__/ImplWrapper/mockSchema.ts
packages/runtime/__tests__/testLib/Input.tsx
packages/runtime/__tests__/testLib/Tabs.tsx
packages/runtime/__tests__/testLib/index.ts
packages/runtime/src/components/_internal/ImplWrapper/UnmountImplWrapper.tsx

when we are using slot's ifCondition, the slot may have
unmount traits result multiple times

fix(runtime): only teardown state when the component is not hidden before this check

---

packages/editor-sdk/src/types/editor.ts
packages/editor-sdk/src/types/operation.ts
packages/editor/src/init.tsx
packages/editor/src/operations/AppModelManager.ts
packages/editor/src/operations/branch/batch.ts
packages/editor/src/operations/index.ts
packages/editor/src/types.ts

Allow the widgets do some operations.

feat: add `doOperations`

---

examples/form/basic.json
examples/form/formInDialog.json
examples/form/formValidation.json
examples/input-components/inputValidation.json
examples/table/tableWithForm.json
packages/runtime/index.html
packages/runtime/src/traits/core/Validation.tsx

- Support more built-in validate functions
- Support custom the validate function
- Support multiple validation rules for a value
- Triggered the validation by methods instead of the value change
- Change the spec struct(breaking changes)

feat: refactor the validation trait (#breaking-chagnes)

---

packages/arco-lib/package.json
packages/arco-lib/src/components/Table/Table.tsx
packages/arco-lib/src/constants/widgets.ts
packages/arco-lib/src/generated/types/Table.ts
packages/arco-lib/src/widgets/TablePrimaryKeyWidget.tsx
packages/arco-lib/src/widgets/index.ts
packages/editor/src/main.tsx
packages/editor/types/widgets.d.ts

Support for specifying a column as a row key and automatic generation of a row key by default

support for automatic generation of `rowKey` or setting from columns

---

packages/editor/__tests__/model/fieldModel.spec.ts
packages/editor/__tests__/validator/component.spec.ts
packages/editor/__tests__/validator/mock.ts
packages/editor/src/AppModel/FieldModel.ts
packages/editor/src/validator/rules/PropertiesRules.ts
packages/editor/src/validator/rules/TraitRules.ts
packages/shared/__tests__/spec.spec.ts
packages/shared/src/utils/spec.ts

1. allow using question mask in expression, like `{{api.fetch?.data}}`.
2. fix the bug that validator cannot validate nested object in expression.
3. fix the bug that validator will warn local variables declared in iife.

Fix some validator bugs

---

packages/editor-sdk/src/components/Form/ArrayTable.tsx

fix(editor-sdk): remove a wrong attribute

---

packages/arco-lib/src/components/Select.tsx
packages/arco-lib/src/generated/types/Select.ts

feat(Select): add title to select option

---

packages/arco-lib/src/components/Collapse.tsx
packages/arco-lib/src/components/Form/FormControl.tsx
packages/arco-lib/src/components/Grid.tsx
packages/arco-lib/src/components/Space.tsx
packages/arco-lib/src/components/Table/Table.tsx
packages/arco-lib/src/components/Tabs.tsx
packages/arco-lib/src/components/_internal/EmptyPlaceholder.tsx

1. add slot key to keep  that `$slot` gets the correct value     
2. add default value to the table, a width of -1 means no setting

add slot key

---

packages/arco-lib/src/components/Table/Table.tsx
packages/arco-lib/src/components/Tabs.tsx

1. add slot key for table
2. remove tabs placeholder

 add slot key for table and remove tabs placeholder

---

packages/arco-lib/src/components/Table/Table.tsx
packages/arco-lib/src/generated/types/Table.ts
packages/arco-lib/src/widgets/TablePrimaryKeyWidget.tsx

1. allow custom rowkey
2. illegal default current page is automatically fixed to 1

Fix the bug of table

---

packages/arco-lib/src/components/Table/Table.tsx

1. only selectedRows should be reset when the data is changed
2. fix: Non-server-side paging should also synchronize the current page state
3. remove selectedRow property

fix(Table): only selectedRows should be reset when the data is changed
